CASE_SIZE = 80
CASE_BORDER = 2

GRID_COLS = 4
GRID_ROWS = 4

GRID_WIDTH = GRID_COLS * (CASE_SIZE + CASE_BORDER + 1)
GRID_HEIGHT = GRID_ROWS * (CASE_SIZE + CASE_BORDER + 1) 

WIDTH = GRID_WIDTH + CASE_SIZE * 3
HEIGHT = GRID_HEIGHT + CASE_SIZE * 3

GRID_X = (WIDTH - GRID_WIDTH) / 2
GRID_Y = (HEIGHT - GRID_HEIGHT) / 2

TPS = 120